global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API 서버 모니터링
  - job_name: 'smartmealtable-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Admin 서버 모니터링  
  - job_name: 'smartmealtable-admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin:8081']
    scrape_interval: 30s
    scrape_timeout: 10s

  # 스케줄러 모니터링
  - job_name: 'smartmealtable-scheduler'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['scheduler:8082']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis 모니터링 (redis_exporter 사용시)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # MySQL 모니터링 (mysqld_exporter 사용시)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']