name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build all modules with Gradle
      run: ./gradlew clean build -x test
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push API Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile.api -t $ECR_REGISTRY/smartmealtable-api:$IMAGE_TAG .
        docker push $ECR_REGISTRY/smartmealtable-api:$IMAGE_TAG
    
    - name: Build and push Admin Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile.admin -t $ECR_REGISTRY/smartmealtable-admin:$IMAGE_TAG .
        docker push $ECR_REGISTRY/smartmealtable-admin:$IMAGE_TAG
    
    - name: Build and push Scheduler Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile.scheduler -t $ECR_REGISTRY/smartmealtable-scheduler:$IMAGE_TAG .
        docker push $ECR_REGISTRY/smartmealtable-scheduler:$IMAGE_TAG
    
    - name: Build and push Crawler Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f Dockerfile.crawler -t $ECR_REGISTRY/smartmealtable-crawler:$IMAGE_TAG .
        docker push $ECR_REGISTRY/smartmealtable-crawler:$IMAGE_TAG
    
    - name: Deploy to EC2 using SSM
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
              "docker pull '"$ECR_REGISTRY"'/smartmealtable-api:'"$IMAGE_TAG"'",
              "docker pull '"$ECR_REGISTRY"'/smartmealtable-admin:'"$IMAGE_TAG"'",
              "docker pull '"$ECR_REGISTRY"'/smartmealtable-scheduler:'"$IMAGE_TAG"'",
              "docker pull '"$ECR_REGISTRY"'/smartmealtable-crawler:'"$IMAGE_TAG"'",
              "docker stop smartmealtable-api || true",
              "docker stop smartmealtable-admin || true",
              "docker stop smartmealtable-scheduler || true",
              "docker rm smartmealtable-api || true",
              "docker rm smartmealtable-admin || true",
              "docker rm smartmealtable-scheduler || true",
              "docker run -d --name smartmealtable-api --network monitoring -p 8080:8080 -e JAVA_OPTS=\"-Xmx512m\" -e SPRING_DATASOURCE_URL=jdbc:mysql://'"${{ secrets.RDS_ENDPOINT }}"'/smartmealtable?useSSL=false\\&serverTimezone=Asia/Seoul\\&allowPublicKeyRetrieval=true -e SPRING_DATASOURCE_USERNAME=smartmeal_user -e SPRING_DATASOURCE_PASSWORD='"${{ secrets.RDS_PASSWORD }}"' -e SPRING_REDIS_HOST=redis -e SPRING_REDIS_PORT=6379 '"$ECR_REGISTRY"'/smartmealtable-api:'"$IMAGE_TAG"'",
              "docker run -d --name smartmealtable-admin --network monitoring -p 8081:8080 -e JAVA_OPTS=\"-Xmx256m\" -e SPRING_DATASOURCE_URL=jdbc:mysql://'"${{ secrets.RDS_ENDPOINT }}"'/smartmealtable?useSSL=false\\&serverTimezone=Asia/Seoul\\&allowPublicKeyRetrieval=true -e SPRING_DATASOURCE_USERNAME=smartmeal_user -e SPRING_DATASOURCE_PASSWORD='"${{ secrets.RDS_PASSWORD }}"' '"$ECR_REGISTRY"'/smartmealtable-admin:'"$IMAGE_TAG"'",
              "docker run -d --name smartmealtable-scheduler --network monitoring -e JAVA_OPTS=\"-Xmx256m\" -e SPRING_DATASOURCE_URL=jdbc:mysql://'"${{ secrets.RDS_ENDPOINT }}"'/smartmealtable?useSSL=false\\&serverTimezone=Asia/Seoul\\&allowPublicKeyRetrieval=true -e SPRING_DATASOURCE_USERNAME=smartmeal_user -e SPRING_DATASOURCE_PASSWORD='"${{ secrets.RDS_PASSWORD }}"' '"$ECR_REGISTRY"'/smartmealtable-scheduler:'"$IMAGE_TAG"'"
            ]
          }'